server:
  port: 9092
spring:
  main:
    allow-bean-definition-overriding: true
dubbo:
  scan:
    base-packages: org.apache.dubbo.springboot.demo.service.impl
  application:
    name: springboot-demo-provider
    qos-port: 0
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 9093