server:
  port: 9094
spring:
  main:
    allow-bean-definition-overriding: true
dubbo:
  scan:
    base-packages: org.apache.dubbo.springboot.demo.controller
  application:
    name: springboot-demo-consumer
    qos-port: 0
  registry:
    id: local-registry
    address: zookeeper://127.0.0.1:2181
  protocol:
    id: dubbo
    name: dubbo
    port: 9095
